# `pydantic_graph.exceptions`

::: pydantic_graph.exceptions
